name: Github Action with a cronjob trigger
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - step 2
      # - step n, use it as the last step
      - uses: gautamkrishnar/keepalive-workflow@2.0.10 # using the workflow with default settings