name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout keepalive branch
        uses: actions/checkout@v4
        with:
          ref: keepalive

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push empty commit
        run: |
          git commit --allow-empty -m "chore: keepalive" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.PAT_PUSH }}@github.com/superTO/twstock-KDJ-generate.git keepalive
