name: 'line-message-api'

on: 
  workflow_dispatch:
  schedule:
    - cron:  "0 5,12 * * *" # 要用臺灣時間減8小時。例如如果要在臺灣的半夜4點執行，則需要設為 "0 20 * * *"

jobs:
  line-notify-send-message:
    # Assign GitHub Environments
    environment: line-message-api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.20'  # 使用 Python 3.9.20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to send LINE message
        run: |
          python main.py --token ${{ secrets.CHANNEL_ACCESS_TOKEN }} --user_id ${{ secrets.USERID }}